/*
 * This source file was generated by the Gradle 'init' task
 */
package com.jdisc.toolchain

import org.gradle.testfixtures.ProjectBuilder
import spock.lang.Specification

/**
 * A simple unit test for the 'org.example.greeting' plugin.
 */
class ClassDependenciesPluginTest extends Specification {
    def "plugin registers task"() {
        given:
        def project = ProjectBuilder.builder().build()

        when:
        project.plugins.apply("com.jdisc.toolchain.class-dependencies")

        then:
        project.pluginManager.hasPlugin("com.jdisc.toolchain.class-dependencies")
    }
}
